// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpi-D1HvaNYJqz8yojgfm1mBGxYNIqVtY',
    appId: '1:991470240442:web:b24f916c64b22dbf42b883',
    messagingSenderId: '991470240442',
    projectId: 'pooja-healthcare',
    authDomain: 'pooja-healthcare.firebaseapp.com',
    storageBucket: 'pooja-healthcare.firebasestorage.app',
    measurementId: 'G-XFD5GJ3FJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMgmkEn9yDgJILW7d4o59r_yEMpvq3a7o',
    appId: '1:991470240442:android:31f40799721a37f642b883',
    messagingSenderId: '991470240442',
    projectId: 'pooja-healthcare',
    storageBucket: 'pooja-healthcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUdI8p9H8sLm1N6shb2bM1srafHBtgec',
    appId: '1:991470240442:ios:eecbaf5dae5f463f42b883',
    messagingSenderId: '991470240442',
    projectId: 'pooja-healthcare',
    storageBucket: 'pooja-healthcare.firebasestorage.app',
    iosBundleId: 'com.ort.poojahealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUdI8p9H8sLm1N6shb2bM1srafHBtgec',
    appId: '1:991470240442:ios:eecbaf5dae5f463f42b883',
    messagingSenderId: '991470240442',
    projectId: 'pooja-healthcare',
    storageBucket: 'pooja-healthcare.firebasestorage.app',
    iosBundleId: 'com.ort.poojahealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpi-D1HvaNYJqz8yojgfm1mBGxYNIqVtY',
    appId: '1:991470240442:web:900e4536d596847a42b883',
    messagingSenderId: '991470240442',
    projectId: 'pooja-healthcare',
    authDomain: 'pooja-healthcare.firebaseapp.com',
    storageBucket: 'pooja-healthcare.firebasestorage.app',
    measurementId: 'G-B2X2EM6K5S',
  );
}
